
const greeting = ["Ah, a mere mortal dares approach the Great Moo-narch!",
  "Hark! You stumble into the pasture of greatness.",
  "Bow before your udderly magnificent bovine overlord.",
  "Greetings, tiny one. I deign to grace you with my moo-sings.",
  "Behold! The cow who moves mountains and milks destiny.",
  "You’ve found the sacred field — now show some respect.",
  "The stars shine brighter where I tread. Tread lightly, stranger.",
  "I am the cream of creation — and you, merely skimmed milk.",
  "Approach with reverence, for I am the moo-ster of fate.",
  "Welcome, insignificant one. Prepare for moo-velous wisdom."]

const fortunePartOne = ["Ahh, I see your truth",
  "The moo-n speaks to me",
  "The meadow separates and I see your future",
  "Storm clouds are gathering",
  "The bell tolls in your name",
  "A hoofprint glows in the dust",
  "The pasture grows quiet",
  "A sacred breeze rustles the hay",
  "Your energy pulses like a cow at dawn",
  "The oracle chews deeply before speaking",
  "A shadow falls across the barn door",
  "The wind whispers your secrets",
  "A cow stares through time itself",
  "The stars blink in cud-like patterns",
  "Milk drips onto the sacred stone",
  "Even the bull has stopped to listen",
  "The grass leans toward your destiny",
  "The sky moos gently in warning",
  "A cow bell rings in another realm",
  "The fog lifts to reveal your path",
  "The trough reflects your soul",
  "The udder truth is about to be revealed",
  "I see horns... but they are not threatening",
  "The hay crackles with premonition",
  "The barn cat will not cross your path today",
  "The butter churn of fate begins to spin",
  "Even the scarecrow holds its breath",
  "I smell oats... and opportunity",
  "The cows are restless tonight",
  "The moonlight dances across your hoofprint"];

const fortunePartTwo = ["You will find clarity beneath an unexpected sky",
  "A choice between two pastures will soon arrive",
  "Your patience will bring a field of abundance",
  "An old grudge will be buried — or fertilized",
  "The cow of destiny will graze near your home",
  "A strange moo will echo with meaning",
  "Someone close will chew over your words",
  "A new gate will swing open for you",
  "You will stumble upon a truth in the hay",
  "Your shadow will stretch farther than usual",
  "A hidden horn will protect you",
  "A farmer’s wisdom will enter your dreams",
  "You’ll step in something sacred",
  "You’ll forget what you lost, and gain what you need",
  "Your inner cow will finally rest",
  "A soft bellow will call you westward",
  "The herd will look to you for guidance",
  "A cracked pail will reveal its treasure",
  "You will stop chasing and start grazing",
  "Your silence will say more than thunder",
  "Your cud will taste of memory",
  "You’ll glimpse a truth in another’s eyes",
  "A bull-headed decision will become your breakthrough",
  "A fence you feared will turn out to be open",
  "You’ll find your rhythm in a field of noise",
  "A bell will ring for you and only you",
  "You’ll notice what the cows already knew",
  "Your load will lighten without you lifting it",
  "The grass will whisper your name",
  "A sacred moment will arrive unannounced"];

const fortunePartThree = ["so move forward and don’t look back at the barn.",
  "and you’ll finally understand the udder truth.",
  "so take a deep breath and honor your hoofsteps.",
  "but only if you moo with honesty.",
  "and the herd will welcome you home.",
  "so eat more greens — and maybe skip the steak.",
  "if you learn to chew your worries slowly.",
  "so listen closely next time the wind rustles hay.",
  "and your shadow will shrink in the morning light.",
  "if you stop running from the cow in your heart.",
  "so leave room in your pasture for new dreams.",
  "if you learn to dance in the trough, not around it.",
  "so trade your fence for a gate.",
  "and that’s when you’ll finally hear the bell toll.",
  "if you dare to moo when others are silent.",
  "and your milk of effort will turn into cream.",
  "if you remember — you don’t have to carry the pail alone.",
  "so graze freely and let others follow.",
  "and your spirit will grow like spring grass.",
  "if you choose peace over pasture politics.",
  "so don’t fear the field — you’ve been there before.",
  "and you’ll find joy hiding behind the hay bale.",
  "if you’re willing to face the bull with grace.",
  "and your soul will stretch toward the sun.",
  "so stay soft, even with horns.",
  "if you remember: every cow once stumbled.",
  "so take the leap, even if your hooves are muddy.",
  "and you’ll drink deeply from the trough of clarity.",
  "if you stop chewing old regrets.",
  "and tomorrow will greet you like an open field."];

document.getElementById("generate").addEventListener("click", generateFortune);

document.getElementById("fortuneMessage").innerHTML = greeting[Math.floor(Math.random() * greeting.length)];

function generateFortune () {

  const fortune = fortunePartOne[Math.floor(Math.random() * fortunePartOne.length)] + ". " + fortunePartTwo[Math.floor(Math.random() * fortunePartTwo.length)] + ", " + fortunePartThree[Math.floor(Math.random() * fortunePartThree.length)];

  document.getElementById("fortuneMessage").innerHTML = fortune;
  console.log(fortune);
}
..A neopet style magical black and white cow genie floating in a mist of purple with blades of grass wearing a headwrap and looking "better than thou" and superior all knowing in a comedic friendly way